<?php
$order_status = ["PAUSED", "RUNNING", "RUNNING_ERROR", "REFUND", "COMPLETED", "PENDING", "PENDING_ERROR", "ERROR", "PENDING_REFUND", "CHECKING_COMPLETED", 'HOLDING', 'CHECKING_WARRANTY', 'ERROR'];
